* Funny Names List
Aaron Thetires (Air in the Tires)
Abbie Birthday (Happy Birthday)
Abe Rudder (Hey Brother)
Abel N. Willan (Able and Willing)
Achilles Punks (I'll Kill These Punks)
Adam Baum
Adam Bomb (Atom Bomb)
Adam Meway (Out of My Way)
Adam Sapple (Adam's Apple)
Adam Zapel
Adam Zapel (adam's apple)
Adolf Oliver Nippils (Ate Off All Of Her Nipples)
Agatha L. Outtathere
Al B. Tross
Al B. Zienya (I'll Be Seeing You)
Al Bino
Al Bino (albino)
Al DePantzeu (I'll De-Pants You)
Al Dente
Al Dente
Al Depantsyoo
Al Fresco
Al Fresco
Al Gore-Rythim (Algorithym)
Al K. Seltzer
Al Kaholic (Alcoholic)
Al Kaseltzer (Alkaseltzer)
Al Kickurass (I'll Kick Your Ass)
Al Killeu (I'll Kill You)
Al Luminum (Aluminum)
Al Nino (El Nino)
Al O'Moaney (Alimony)
Alec Tricity (Electricity)
Alex Blaine Layder (I'll Explain Later)
Alf A. Romeo
Alf A. Romeo (Alpha Romeo)
Alf Abet (Alphabet)
Ali Gaither, Ali Katt
Ali Gator (Ali Gator)
Ali Katt (alley cat)
Allen Rench
Allota Fagina (A lot of vagina)
Alpha Kenny Wun (I'll Fuck Anyone)
Amanda B. Recandwithe (A Man to Be Reckoned With)
Amanda B. Reckonwith
Amanda Hugnkiss (A Man to Hug and Kiss)
Amanda Lay (A Man To Lay)
Amanda Lay (real person)
Amanda Lynn (a mandolin)
Amanda Lynn (a mandolin)
Amber Green
Andy Friese (antifreeze)
Andy Friese (as in antifreeze, a real race car driver)
Andy Gravity (Anti-Gravity)
Andy Structible (Indestructible)
Anita Bath (I Need A Bath)
Anita Bath (I need a bath)
Anita Bathe, Anita Bohn, Anita Dick, Anita Friske, Anita Hanke (real person), Anita Goodman, Anita Hoare
Anita Cock (I need a cock)
Anita Handjob (or Fix or Blowjob or you-name-it)
Anita Hoare (I Need A Whore)
Anita Job, Anita Knapp, Anita Lay, Anita Little, Anita Mann, Anita Mandalay, Anita Plummer
Ann B. Dextrous (Ambidextrous)
Ann Chovie (Anchovy)
Ann Tartica (Antartica)
Anna Conda
Anna Fender (an offender)
Anna Graham
Anna Linjection (Anal Injection)
Anna Mull (Animal)
Anna Prentice
Anna Prentice (an apprentice)
Anna Prentice (an apprentice)
Anna Recksiek (anorexic)
Anna Recksiek (anorexic) 
Anna Rexiya (Anorexia)
Anna Sasin
Anna Sasin
Anna Sasin (an assassin)
Anna Septic
Annabelle Rang
Anne Ball
Anne T. Lope (Antelope)
Anne Teak
Anne Teak (antique)
Anne Teake
Annette Curtain
Annette Curtain (a net curtain)
Annette Kirton
Annette Kirton - a net curtain
Annie Buddyhome (Anybody Home)
Annie Howe, Annie Matter
Annie Mah (Enema)
April May (a real person I knew in high school)
April Schauer (allegedly a real person)
Arch N. Emmy
Aretha Holly
Aretha Holly (a wreath of holly)
Ariel Hassle (A Real Hassle)
Armand Hammer
Art Exhibit
Art Major, Art Painter, Art Sellers
Artie Choke
Artie Choke (Artichoke)
Ash Hull
Athol, Massachusetts (real town)
Aunty Biotic (Anti-Biotic)
Ava Jyna
Ayma Dommy (I'm A Dummy)
Ayma Moron (I'm a Moron)
B.A. Ware
Barb Dwyer
Barb Dwyer (Barbed Wire)
Barb Dwyer (barbed wire)
Barb Dwyer - barbed wire
Barb E. Cue (Barbecue)
Barb E. Dahl
Barb E. Dahl (Barbie doll)
Barb. D wyer
Barbara Dwyer
Barbara Seville
Barbara Seville (barber of Seville)
Barry Cade
Barry Cade (barricade)
Barry D'Alive (Buried Alive)
Barry D. Hatchett (Bury the Hatchett)
Barry Shmelly (Very Smelly)
Bart Ender (Bartender)
Bea Minor (be a miner)
Bea Minor and Dee Major
Bea O'Problem (B.O. Problem)
Bea Sting (Bee Sting)
Beau Archer, Beau Tye
Beau Vine (Bovine)
Bella Donna Drink
Ben Crobbery (Bank Robbery)
Ben D. Fender
Ben Dover (Bend Over)
Ben Dover (bend over)
Ben Dover, Ben Down, Eileen Dover, Skip Dover
Ben Lyon (Been lieing)
Ben Marcata (a musical term)
Ben O'Drill (Benadryl)
Ben Thair (Been There)
Bernd Onions
Bertha D. Blues
Bess Eaton (donut shop chain)
Bess Twishes (Best Wishes)
Betty Bangzer (Bet He Bangs Her)
Betty Beatzer (Bet He Beats Her)
Betty Humpser (Bet He Humps Her)
Biff Wellington
Bill Board
Bill Board
Bill Board (Billboard)
Bill Ding
Bill Ding (Building)
Bill Ding (building)
Bill Foldes
Bill Leeake (Belly Ache)
Bill Loney
Bill Loney
Bill Loney (baloney)
Bill Lowney (Bologna)
Bill Overdew
Billy Rubin
Bjorn Free (Born Free)
Bo D. Satva 
Bo Nessround (Bonus Round)
Bob Apple
Bob Apple
Bob Frapples (Bob for Apples)
Bob Inforapples 
Bob Katz (bob cats)
Bob Katz, Tom Katz, Kitty Katz
Bob Sledd
Bonnie Ann Clyde
Bonnie Beaver, MD - she's an Ob/Gyn of course!
Bowen Arrow (Bow and Arrow)
Boyd Schidt (Bird Shit)
Brad Hammer (carpenter joke)
Brandon Cattell (branding cattle)
Brandon Cattell, Brandon Irons
Brandy Anne Koch (Brandy and Coke)
Brandy Bottle
Brandy D. Cantor
Brandy D. Cantor (brandy decanter) 
Braxton Hicks
Brice Tagg (Price Tag)
Brighton Early
Brighton Early (Bright and Early)
British car Morris Minor
Brock Lee
Brock Lee (broccoli) 
Brook Lynn Bridge (Brooklyn Bridge)
Brooke Trout
Brooke Trout (brook trout)
Brooke Waters
Bruce Easley
Bryony
Bud Light
Bud Weiser (Budweiser)
Bud Wieser (real college math teacher)
Buddy Booth 
Buddy System
Bunny Hare
Burnedette Down (Burnt it Down)
Buster Cherry (Bust her Cherry)
Buster Cherry, Buster Hyman
Buster Hymen (Bust her Hymen)
C. Good (alledgedly a real eye doctor)
C. Senor
C. Worthy
C. Write (another alleged optician)
Cal Culator (Calculator...duh)
Cal Efornia (California)
Cal Seeium (Calcium)
Cam Payne
Cam Payne (campaign)
Cammie Sole
Candace Spencer (can dispenser)
Candice B. DePlace (Can This Be The Place)
Candice B. Fureal (Can This Be For Real)
Candy Barr (candy bar) 
Candy Barr, Candy Baskett, Candy Kane, Candy Sweet
Candy Kane (candy cane)
Cara Sterio (alleged real person)
Cara Van
Carl Arm (Car Alarm)
Carlotta Tendant (Car Lot Attendant)
Carmen Ghia
Carol Tune.
Carra S. Midown (Caress Me Down)
Carrie Couture (caricature)
Carrie Dababi ("carry the baby" - Dababi is an Egyptian name)
Carrie DeKoffin (Carry the Coffin)
Carrie Oakey
Carrie Oakey (Karaoke)
Carrie Oakey (karaoke)
Carrie Oakey - karaoke
Carson O. Gin (Carcinogen)
Casey Deeya (Quesadilla)
Casey Macy
Casey Needzit (In Case He Needs It)
Cass Trate
Chad Terbocks (Chatterbox)
Chad Ticket
Chanda Lear (Chandalear)
Charity Case
Cheri Pitts (cherry pits)
Cheri Pitts, Harry Pitts
Chi Spurger (Cheeseburger)
Chip Munk
Chip Stone (sculptor)
Chris Coe
Chris Cross
Chris Cross
Chris Ko (Crisco)
Chris Mass (Christmas)
Chris P. Bacon
Chris P. Bacon (crispy bacon)
Chris P. Nugget (Crispy Nugget)
Chris P. Wheatzenraisins 
Chrystal Glass
Chuck Mysak (Chuck My Sack)
Chuck Roast (Hmmm...Chuck Roast?)
Chuck U. Farley
Chuck Waggon
Claire Annette (clarinet)
Claire Annette Reed
Claire DeAir (Clear the Air)
Claire Voyance
Clara Nett (Clarinet)
Clara Sabell (Clear as a Bell)
Claude N. Skretchem (Clawed and Scratched Them)
Clint Toris (Clitoris)
Cody Pendant (Co-Dependant)
Cole Durkee
Cole Kuts
Cole Kutz (Cold cuts) See
Colette A. Day
Colin Allcars (Calling all Cars)
Colleen Cardd (Calling Card)
Connie Lingus
Connie Lingus (Cunnilingus)
Constance Noring
Constance Noring (constant snoring)
Corey Ander
Corey O. Graff
Count Dunn, Count Orff
Coyne Flatt (real person)
Craig Potz (Crackpots)
Craven Moorehead
Craven Moorehead (Craving More Head)
Crystal Ball
Crystal Ball (Crystal Ball)
Crystal Ball (real person)
Crystal Claire Waters
Crystal Glass, Crystal Metheney, Crystal Snow
Curt N. Rodd (Curtain Rod)
Curt Zee (Curtsy)
Cy Burns (Sideburns)
Cy Kosis (Psychosis)
D. Kay, DDS
D. Liver
Daisy Chain
Daisy Picking
Dale E. Bread (Daily Bread)
Dan D. Lyon (Dandelion)
Dan D. Lyons (dandelions)
Dan D. Lyons, Dan Deline
Dan Druff
Dan Druff
Dan Druff (Dandruff)
Dan Druff (dandruff)
Dan Geruss (Dangerous)
Dan Gleebitz (Dangly Bits)
Dan Saul Knight
Danielle Soloud (Don't Yell So Loud)
Darius Lesgettham (There He Is, Let's Get Him)
Darrell B. Moore (There'll be More)
Darren Deeds
Darryl Likt
Daryl Lect (Derelict)
Daryl Rhea
Dawn Hobbs
Dawn Keebals (Donkey Balls)
Dear Beloved (real person)
Dee Capitated (Decapitated)
Dee Faced (Defaced)
Dee Flower
Dee Sember (December)
Dee Zaster
Denise Shaking
Dennis Toffice (Dentist Office)
Denny Juan Heredatt (Did Anyone Hear That?)
Des Buratto (Desperado)
Di O'Bolic (Diobolic)
Diane Toluvia (Dyin' to Love Ya)
Dick Bender (real sports person)
Dick Burns
Dick Burns
Dick Bush (real person)
Dick Cumoff (Dick Come Off)
Dick Face
Dick Finder (real name of a urologist)
Dick Gozinia (Dick Goes In Ya)
Dick Head (Uhhh...Dick Head)
Dick Head, Dick Hertz
Dick Hunter (my junior high principal - really!)
Dick Hyman (famous jazz musician)
Dick Long
Dick Mussell
Dick N. Cider (Dick Inside Her)
Dick Pole (real major league baseball player)
Dick Pound
Dick Rasch (real person)
Dick Smoker 
Dick Swett
Dick Tater (Dictator)
Dick Tator
Dick Trickle (real person, a NASCAR driver)
Dick Wipe
Dick Wood (real person, emailed me)
Dick Zucker (Dick Sucker...You Know Who You Are)
Dickson Yamada
Didi Reelydoit (Did He Really Do It?)
Dilbert Pickles
Dinah Might
Dinah Soares
Dinah Soares (dinosaurs)
Dinah Sore (Dinosaur)
Dixon, Cox, and Peters (law firm)
Doll R. Bill...(Dollar Bill)
Don Key
Don Key (donkey)
Don Thatt (Done That)
Donald Duck
Donny Brook
DooLittle & Dalley (Real Estate Agent in England)
Doris Schutt (Doris Open...)
Doug & Phil Updegrave (yes, this is a legitimate last name)
Doug Graves
Doug Graves
Doug Graves (Dug Graves)
Doug Graves (dug graves)
Doug Hole
Doug Hole
Doug Hole (dug hole)
Doug Love-Fitzhugh
Doug Witherspoon
Douglas Furr
Douglas S. Halfempty (The Glass is Half Empty)
Dr. & Dr. Doctor (real married doctors from Norwalk, CT)
Dr. Baldock (of course he's a Urologist)
Dr. Bender (Chiropracter)
Dr. Butcher
Dr. Croak
Dr. Croak
Dr. DeKay, DDS
Dr. E. Ville
Dr. Frank Bonebreak (real doctor)
Dr. Franklin Stein (real doctor)
Dr. Gass (allegedly a real anesthesiologist)
Dr. Gutstein
Dr. Hanus
Dr. Harry C. Beaver (real OB/GYN, retired now)
Dr. Hurt (real pediatrician in Saginaw, MI)
Dr. Hymen
Dr. I. Ball (optometrist)
Dr. Kauff
Dr. Look (real opthalmologist in Hawaii)
Dr. Looney - a psychiatrist of course!
Dr. Payne (Dr Pain)
Dr. Payne (plastic surgeon in Sandusky, OH)
Dr. Pullham
Dr. Robert Fallis, real doctor who does vasectomies)
Dr. Shelly Fingerhood (real OB/GYN)
Dr. Slaughter
Dr. Steven Sumey (Dr. sue me, real person in Fairmont, MN)
Dr. Surgeon (another real doctor from Stamford, CT)
Drew Blood (Drew Blood)
Drew Peacock
Drew Peacock
Drew Peacock (Droopy Cock)
Duane DeVane (Drain the Vain)
Duane Pipe
Duane Pipe (drain pipe)
Dustin D. Furniture (Dusting the Furniture)
Dusty Carr
Dusty Carr, Dusty Rhodes
Dusty Rhodes (dusty roads)
Dusty Sandmann (real person, submitted by his dad Roger Sandmann)
Dwayne Pipe
Dwayne Pipes (Drain Pipes)
Dylan Weed (Dealin' Weed)
Earl E. Bird
Earl E. Bird (early bird)
Earl E. Byrd (Early Bird)
Earl Lee Riser
Earl Lee Riser (early riser)
Easton West (and of course Weston East)
Easton West (east and west)
Eaton Wright and Liv Good
Ebony Wood
Ed Ible (Edible)
Ed Jewcation (Education)
Ed Venture (Adventure)
Eda Dick (Eat a dick)
Edna May (or may not)
Edna May (or may not)
Edward Z. Filler, DDS
Eileen Dover
Eileen Dover (I Leaned Over)
Eileen Dover (I leaned over)
Eli Ondefloor
Ella Vader
Ella Vader (Elevator)
Ella Vader (elevator)
Elle O'Quent (Eloquent)
Ellie Noise (Illinois)
Ellis Dee (L.S.D)
Elmer Sklue
Elmer Sklue (Elmer's Glue)
Emerald Stone
Emile Eaton (a meal eaten)
Emma Roids (Hemorrhoids)
Emma Royds
Eric Shinn
Eric Shun (Erection)
Ernie Coli (E. Coli) owns a Mexican restaurant
Estelle Hertz (it still hurts)
Ethel L. Cahall
Etta Booger
Evan Keel
Evan Lee Arps (Heavenly Harps)
Evans Gayte (Heavan's Gate)
Eve Hill (Evil)
Eve Ning (Evening)
Eve O'Lution (Evolution)
Ewan Whatarmy (You and What Army?)
Faith Christian
Fanny O'Rear, Fanny Hertz
Fanny Shining
Father A. Long
Father of boxer Max
Faye Kinnitt (Faking It)
Faye Slift (Face Lift)
Faye Tallity (Fatality)
Felix Austead (feel exhausted)
Ferris Wheeler
Fletcher Bisceps (Flex Your Bisceps)
Flint Sparks
Fonda Dicks (a real women's league basketball player)
Ford Parker
Ford Parker
Forrest Green
Forrest Green (forest green)
Forrest Ranger
Foster Child
Frank Enstein
Frank Furter
Frank Furter (Frankfurter)
Frank N. Beans
Frank N. Sense
Frank N. Stein (Frankenstein)
Freida Convict (Free the Convict)
Frieda Slaves
Gabe Asher (Gay Basher)
Gabe Barr (Gay Bar)
Gae Hooker (allegedly real surgical prep nurse)
Gail Force
Gail Storm
Gail Storm (Wendy Storm, Dusty Storm and Rory Storm)
Gaye Barr
Gaye Barr (gay bar)
Gaye Jolly (and her sister Holly Jolly)
Gayle Storm
Gene E. Yuss (Genius)
Gene Poole
Gene Poole (Gene Pool)
Geoff L. Tavish (Gefilte fish)
George Washington Sleptier
Gil Fish
Gil T. Azell (Guilty as Hell)
Ginger Rayl, Ginger Snapp, Ginger Vitus
Ginger Vitis (Gingervitis)
Gladys
Gladys C. Hughes (glad to see you)
Gladys Eeya (Glad to See Ya)
Godiva Headache
Gus Comzadia (Gas Comes Outta Ya)
Gus Tofwin (Gust of Wind)
H. Wayne Carver, MD (Connecticut medical examiner who carves up dead people.)
Hal E. Luya (Hallelujah)
Hal Jalikakick (How'd ya like a kick)
Hamilton Burger (Ham Burger, character on the old Perry Mason TV series)
Hammond Eggs
Hammond Eggs (Ham and Eggs)
Hank E. Panky (Hanky Panky)
Harden Thicke
Hare Brain
Harley Davidson
Harmon Ikka (Harmonica)
Harold Assman (and you thought that Seinfeld episode was just a joke)
Harris Mint (Harassment)
Harrison Fire (Hair is on Fire)
Harry Armand Bach
Harry Baals (real person)
Harry Balzac (Hairy Ball Sack)
Harry Beard, Harry Beaver, Harry Butts
Harry Caray (famous sports announcer)
Harry Chest, Harry Cox, Harry Dangler, Harry Johnson, Harry Legg, Harry Hooker, Harry P. Ness, Harry Peters, Harry Lipp, Harry Sachs
Harry P. Ness
Harry R. M. Pitts
Harry Rump (real plumber from Freemont, Maine)
Harry Weiner (Hairy Wiener)
Hayden Seek (Hide & Seek)
Haywood Jablowme (Hey, Would You Blow Me?)
Haywood Jashootmee (Hey Would You Shoot Me?)
Hazel Nutt
Hazel Nutt (hazel nut)
Hazle Nutt
Heather N. Yonn
Hedda A. Borshun
Heidi Clare
Heidi Clare (I declare)
Hein Noon (High Noon)
Helen Back
Helen Back (Hell and Back)
Helen Beck (Hell and back)
Helen Highwater
Helen Waite (credit manager - if you want credit go to Helen Waite)
Helen Wiells (hell on wheels)
Helena Hanbaskett (Hell In A Hand Basket)
Henador Titzhoff (He Gnawed Her Tits Off)
Herb E. Side (Herbiside)
Herb Farmer, Herb Rice
Herbie Hind (Her Behind)
Herbie Voor (Herbivore)
Hilda Climb
Holden Mcgroin (Holding My Groin)
Holly Day (holiday)
Holly Day, Holly Wood
Holly Dayin (Holiday Inn)
Holly McRell
Holly Wood (Hollywood)
Holly Wood (Hollywood)
Homan Provement (Home Improvent)
Homer Sexual
Homer Sexual (Homosexual)
Honey Bee
Hope Ferterbest
Howard I. No (How Would I Know?)
Howe D. Pardner (Howdy Partner)
Howie Doohan
Hu Flung Pu (Who Flung Poo?)
Huang Annsaw (Wrong Answer)
Hugh Beeotch (You Bitch)
Hugh G. Rection
Hugh G. Rection (Huge Erection)
Hugh Jass
Hugh Jass (Huge Ass)
Hugh Jass (huge ass)
Hugh Jorgan
Hugh Morris (a "humorous" name, thanks to Shaun Oriold)
Hugh Mungous (Humungous)
Hugh deMann (You Da Man!)
Hugo First (You Go First)
Hy Ball
Hy Gene (Hygiene)
Hy Lowe, Bea Lowe
Hy Marx (scholar), Hy Price
I. Juan Tabloya
I. Lasch
I. Pullem (allegedly a real dentist)
I. Ron Stomach (Iron Stomach)
I.D. Clair
I.M. Boring
I.P. Freehly (I Pee Freely)
I.P. Freely, I.P. Daly
Ida Hoe (Idaho)
Ida Whana (I Don't Want to)
Igor Beaver (Eager Beaver)
Ileane Wright, Ilene South (West, East...)
Ilene Dover (I Leaned Over)
Ima B. Leever (I'm A Believer)
Ima Gaye-Barr
Ima Hogg (a real person, daughter of a Texas governor)
Ima Kettle
Ima Klotz and her sister, Sasha Klotz
Iona Ford
Iona Frisbee (alledgedly a real person)
Iona Stonehouse (also alledgedly a real person)
Ira Fuse (I Refuse)
Isadore Bell (a real person)
Ivan Itchinanus (I Hate an Itching Anus)
Ivan Oder
Ivana Humpalot (I Want to Hump A Lot)
Ivana Kutchukokoff (I Wanna Cut Your Cock Off)
Ivana Mandic (a real basketball player)
Ivana Tinkle ( I Want to Tinkle)
Ivy Leage
Izzy Backyet (Is He Back Yet?)
Izzy Cumming (Is He Cumming)
Jack Dupp (Jacked Up)
Jack Goff (my uncle - no kidding!)
Jack Haas
Jack Hammer
Jack Hoff
Jack Knoff
Jack Koff (Jack Off)
Jack Off
Jack Pot (Jackpot!)
Jack Pott
Jack Tupp (the perfect name for a car mechanic)
Jacklyn Hyde
Jacques Strap (Jock Strap)
Jade Stone
Jan U. Wharry (January)
Jane Linkfence (Chainlink Fence)
Janet Uppissass
Jaqueline Hyde (Jekyll and Hyde)
Jasmine Flowers
Jasmine Rice (I found this one in my cupboard)
Jawana Die (Do Ya Wanna Die?)
Jay Bird
Jay Walker
Jay Walker (Uhhh...Jay Walker)
Jean Poole
Jean Poole (gene pool)
Jeanette Akenja-Nearing (Genetic Engineering)
Jed Dye (Jedi)
Jed Dye (Jedi)
Jed I. Knight (Jedi Knight)
Jeff Healitt (Did Ya Feel It?)
Jenny Tull
Jenny Tull (Genital)
Jerry Atrick
Jerry Atrics (Geriatrics)
Jim Laucher (gym locker)
Jim Nasium (Gymnasium)
Jim Shorts (gym short)
Jim Shorts, Jim Shu, Jim Sox
Jimmy DeLocke
Jo King
Jo King
Jo King (joking)
Joanna Hand (D'ya Want a Hand?)
Joaquin DeFlores (walkin' the floors)
Joe Czarfunee (Jokes Are Funny)
Joe Kerr (joker)
Joe King 
Joe King (Joking)
Jonah Wales
Jordan Rivers
Jose Frayed (Who's Afraid)
Joy Anna DeLight
Joy Kil
Joy Rider
Juan De Hattatime(One Day at a Time)
Juan Fortharoad (One For the Road)
Juan Morefore DeRhode
Juan Nightstand (One Night Stant)
Juana Bea (Wanna-Be)
Judy Punch
June Bugg
Justin Case
Justin Case
Justin Case (Just in Case)
Justin Case (just in case)
Justin Case, Justin Casey Howells, Justin Hale, Justin Inch, Justin Miles North (just ten miles north), Justin Sane, Justin Time, 
Justin Credible (Just Incredible)
Justin Thyme
Justin Time (just in time)
Justin Tune
Kandi Apple
Kareem O'Weet (Cream of Wheat)
Katherine (Kat) Toy (a real person)
Katy Litter
Kay Bull
Kay Mart
Kay Neine (Canine)
Kay O'Pectate (Kaopectate)
Kaye Ken Cofe (Cake and Coffee)
Keelan Early (dying young) - real person who submitted his own name
Kelly Green
Ken Dahl
Ken Oppenner (Can Opener)
Kenitra Bush (Can I Eat Your Bush)
Kenny Dewitt (Can He Do It?)
Kenny Fakur (Can he Fuck her)
Kenny Penny
Kent C. Strait (an optometrist, of course!)
Kent Cook (Can't Cook)
Kenya Dewit
Kerry Oki
Kim Payne Slogan (Campaign Slogan)
Kimberley Mine
Kimmy Head (Give Me Head)
King Queene
Kitty Katz (kitty cats)
Kristie Hannity (Christianity)
Kurt Remarque
Lafayette S. Cadrille
Lake Speed (a real person, NASCAR race car driver)
Lance Boyle
Lance Boyle (lance boil)
Lance Boyle, Lance Butts
Lance Lyde (Landslide)
Laura Lynn Hardy (Laurel and Hardy)
Laura Lynne Hardy, Laurel Ann Hardy
Laura Norder
Laura Norder (law and order)
Laurence Getzoff
Lee Keyrear (Leaky Rear)
Lee Nover (Lean Over)
Leigh King (leaking)
Leigh King (leaking)
Len DeHande (Lend a Hand)
Leo Tarred (Leotard)
Les Moore
Les Payne - should be an anesthesiologist
Les Plack, a real dentist
Levon Coates
Lewis N. Clark (real person, he told me he drives an Explorer)
Lily Livard (Lily Livered)
Lily Pond
Lina Ginster (allegedly real)
Lindsay Doyle (There are "Manny Moore" funny names in the linked video.)
Lindsay Doyle (linseed oil)
Lisa Carr, Kitty Carr, Otto Carr, Parker Carr
Lisa Ford, Lisa Honda, Iona Corolla, etc.
Lisa May Boyle, Lisa May Dye
Lisa Neucar (Lease a New Car)
Liv Long
Liz Onnia (Lasagna)
Lois Price (bargain shopper) and her husband Hy Price
Lon Moore (Lawn Mower)
Lori Truck
Lorry Truck or
Lotta Zits
Lou Briccant (Lubricant)
Lou Dan Obseen 
Lou Pole
Lou Sirr (Loser)
Lou Stooth (Loose Tooth)
Lou Zar (loser)
Louise E. Anna (Louisiana)
Lowden Clear
Lowden Clear (Loud and Clear)
Luckey, Chance, a real doctor
Lucy Fer
Luke Adam Go (Look at Him Go)
Luke Atmyass (Look At My Ass)
Luke Warm
Luke Warm
Lulu Anna Bitcrazy
Luna Tick (Lunatic)
Lyle Ike Adogg (Lie Like a Dog)
Lyn
Lynn C. Doyle
Lynn Guini (Linguini)
Lynn Meabuck (Lend Me a Buck)
Lynn O. Liam
M. Balmer
M.T. Toombe
Mabel Syrup (Maple Syrup)
Macon Paine (real name - Google it)
Madame Crotch (My Damn Crotch)
Madka Owdiseez (Mad Cow Disease)
Mandy Lifeboats
Manny Bones
Manny Kinn
Manuel Labor (Manual labor)
Marco DeStinkshun
Marcus Absent
Marcus Absent (Mark Us Absent)
Marge Innastraightline (March in a Straight Line)
Marguerite DeVille (Margaritaville)
Marion Money (Marrying Money)
Marj Oram
Mark A. Roni
Mark Mywords (Mark My Words)
Mark Skid (Skid, Mark)
Mark Z. Spot (Mark The Spot)
Marlon Fisher
Marsha Dimes (March of Dimes)
Marsha Dimes (march of dimes)
Marsha Mellow
Marsha Mellow (marshmallow) 
Marshall Law
Marshall Law
Martha Fokker (Motherfucker)
Marty Graw
Marv Ellis
Mary A. Richman
Mary Ann Bright Trina Corder ($3.25)
Mary Annette Woodin
Mary Christmas
Mary Christmas (Merry Christmas)
Mary Christmas (merry christmas)
Mary Gold
Mary Gold (Marigold)
Mary Juana (Marijuana)
Mary Ott (Marriot)
Mary Ott (Marriot)
Mary Thonn (Marathon)
Mason Jarr
Master Bates (Masturbates)
Matt Tress
Maude L.T. Ford
Maurice Minor
Max E. Mumm (Maximum)
Max E. Pad (Maxi Pad)
Max Little
Max Power
Max Power
May Day
May Day
May Furst
May Furst (May first)
May I. Tutchem (May I Touch Them?)
May K. Fist
May O'Nays (Mayonaise)
Megan Bacon (Makin' Bacon)
Mel Function
Mel Keetehts (Milky Tits)
Mel Loewe
Mel Loewe (mellow)
Mel Practiss (Malpractice)
Melanie Letters
Melba Crisp (real person who emailed me)
Melissa Tothis (Ma, Listen to This)
Melody Music
Mia Hamm (a real person)
Michael Otto Nuys
Michael Toris (My Clitoris)
Michelle Lynn (Michelin)
Midas Well (Might As Well...)
Mike Czech (mic check)
Mike Easter
Mike Hunt
Mike Hunt (My Cunt)
Mike Ockhurts (My Cock Hurts)
Mike Ocksmall (My Cock's Small)
Mike Raffone
Mike Reinhart (My Cryin' Heart - sounds like it could be a country song)
Mike Rohsopht (Microsoft)
Mike Rotch
Mike Rotchburns (My Crotch Burns)
Mike Stand 
Mike Stand (a real person)
Mike Sweeney (sounds as Mike's weenie), famous baseball player
Milly Graham
Milly Meter (Millimeter)
Milton Yermouth
Minnie Skurt (Miniskirt)
Minny van Gogh
Minny van Gogh (mini van go)
Miss Alanius (Miscellaneous)
Missy Sippy (and her mom, Mrs. Sippy)
Mister Bates
Misty C. Shore (a real person), Rocky Shore, Sandy C. Shore (another real person)
Misty Meanor (Misdemeanor)
Misty Shore (along with Rocky and Sandy)
Misty Waters 
Misty Waters (a real person)
Mitch Again (Michigan)
Miya Buttreaks (My Butt Reaks)
Mo Lestor
Mo Lestor (molester)
Moe B. Dick
Moe DeLawn (Moe the Lawn)
Moe Lester (Molester)
Moe Skeeto (Mosquito)
Moe Telsiks (Motel Six)
Molly Kuehl
Mona Little, and after marriage Mona Little-Moore (or Mona Lott and Mona Lott-Moore)
Mona Lott
Mona Lott (moan a lot)
Monica Monica (real person)
Morey Bund
Morgan U. Canhandle
Mort Tallity (Mortality)
Muddy Waters 
Muddy Waters (famous blues singer, real name McKinley Morganfield)
Myles Long
Myles Long (miles long)
Myra Maines (My Remains)
Myra Mains
Mysha Long (My Shlong)
Nadia Seymour (Now do you see more?)
Nancy Ann Cianci
Nat Sass
Neal Down
Neil B. Formy (Kneel Before Me)
Neil Down (kneel down)
Neil Down, Neil Crouch
Neil Dupre (kneel to pray)
Neil McNeil (submitted by his cousin)
Nelly
Neve Adda (Nevada)
Nick Cut
Nick L. Andime (Nickel and Dime)
Nick O'Teen (Nicotine)
Nick O. Time
Nick Ovtime (Nick Of Time)
Nida Lyte (Need a Light)
Nina Levin (911)
NoSmo King*
Noah Lott (know a lot)
Noah Riddle, Noah Lott
Nora Bone
Norma Leigh Lucid
Norma Leigh Lucid (normally lucid)
Norman Knight
Norman Knight - a friend of Will and Guy's.
Olga Fokyrcelf
Olin DeMotor
Olive Branch
Olive Green
Olive Hoyl
Olive Yew (I love you)
Olive Yew (I love you)
Oliver Closeoff (All of her Clothes Off)
Oliver Sutton (all of a sudden)
Oliver Sutton (all of a sudden)
Ophelia Payne
Ophelia Titzoff (I'll Feel Your Tits Off)
Opie Umsgood (Opium's Good)
Oren Jellow
Orson Carte
Orson Carte (horse and cart)
Oscar Ruitt
Otto B. Kilt (Ought to be Killed)
Otto Graf
Otto Graf (autograph)
Otto Whackew (Ought to Whack You)
Owen Big, Owen Cash, Owen Moore (should be tax collectors)
Owen Money
Owen Moore (owing more)
P. Brain
P. Ness, A. Ness
Paige Turner
Paige Turner (Page Turner)
Paige Turner (page turner)
Papa Boner (Pop a Boner)
Paris Plaster
Park A. Studebaker
Pat Downe 
Pat Downe (a real person)
Pat Fanny
Pat Hiscock
Pat May Weiner
Pat McCann
Pat McGroin
Pat Myckok (Pat My Cock)
Pat Pending
Patience Wait (a real person)
Patty Meltt (Umm....Patty Melt)
Patty O'Furniture (Patio Furniture)
Pearl Button
Pearl Button
Pearl Button
Pearl E White (Pearly White)
Pearl E. Gates (pearly gates)
Pearl E. Gates(Pearly Gates)
Pearl E. Gates, Pearl E. White
Pearl E. White (pearly white)
Pearl E. Whites
Peg Legge
Peg Legge (peg leg)
Penny Bunn
Penny Dollar, Bill Dollar (real people)
Penny Lane
Penny Lane, Penny Nichols, Penny Profit, Penny Wise
Penny Whistler
Penny Wise
Penny Wise
Pepe C. Cola
Pepe Roni
Pepe Roni
Peppy Roni (Pepperoni)
Perry Mecium
Pete Moss
Pete Moss and his son Forest
Pete Zaria (Pizzeria)
Peter Guzzinia
Peter Johnson (a real announcer on public radio), Dick Johnson
Peter Pantz (Peed her pants)
Peter Peed
Peter Wacko, DDS (real dentist in Calgary, AB, Canada)
Phil A. Delphia (Philadelphia)
Phil A. Mignon (Filet mignon) 
Phil Atio (Fellatio)
Phil Bowles (must be a pot dealer)
Phil D'Grave
Phil DeGrave (Fill the grave)
Phil Down (Feel Down)
Phil Graves (cemetery employee, works with his brother Doug Graves)
Phil Hole
Phil Lattio
Phil McCracken (Fill My Crack In)
Phil Myez (Feel My Ass)
Phil Mypockets (Fill my pockets)
Phil N. Underwear
Phil Rupp
Phil Wright, DDS (real dentist in Anchorage, AK)
Phillip D. Bagg (partner of Robin Banks below)
Phillip McCrevice (Fill up my Crevice)
Phyllis Schlong (Feel his Shlong)
Pierce Cox (ouch!)
Pierce Deere
Pierce Hart
Polly Dent
Polly Ester
Polly Ester (polyester) 
Polly Esther Pantts (Polyester Slacks)
Poppa Woody (Pop A Woody)
Poppy Seeds
Post, Mark
Price Wright (another real person)
Priti Manek
Priti Manek ("pretty manic", real doctor in Houston, TX)
Prudence Island
Pussy Galore (Well...What the hell do you think it means?!)
Quimby Ingmeen (Quit Being Mean)
Quint S. Henschel (Quintessential)
Quinton Chingme (Quit Touching Me)
Quinton Plates (Contemplates)
R. M. Pitt
R. Sitch
R. Slicker
Rachel DeScrimination (Racial Descrimination)
Randy Guy
Randy Lover
Raney Schauer
Ray Gunn
Ray Gunn
Ray Gunn came very close to inclusion in this top ten - just Jo King.
Ray N. Carnation (Reincarnation)
Ray Pugh (Rape You)
Ray Zenz (raisins)
Raynor Schein
Raynor Schein (rain or shine)
Real name of Will's first girl friend (age 5)
Reed Toomey (read to me)
Reid Enright
Renee Sance (Renaisance)
Rex Easley (reportedly a real traffic safety teacher at Kamiakin High, Kennewick, WA)
Rex Karrs
Rhea Curran
Rhea Pollster
Rhoda Booke, Rita Booke
Rhoda Mule
Rich Feller, Rich Guy, Rich Kidd, Rich Mann
Richard Chopp (real Urologist in Austin, TX, does vasectomies)
Richard P. Cox (real person)
Rick Kleiner (Recliner)
Rick O'Shea
Rick O'Shea
Rick O'Shea (Ricochet)
Rick O'Shea - as in "ricochet" of a bullet
Rick Shaw
Rick Shaw (rickshaw) 
Ricky T. Ladder
Rip Tile (Reptile)
Rip Torn
Rip Torn 
Rita Book (Read a Book)
Rita Buch, Rita Story
Rob A. Bank
Rob Banks
Robert and Reginald Soles (allegedly real brothers: R. Soles)
Robin Andis Merryman
Robin Banks (Robbing Banks)
Robin Banks, Rob Banks, Robin Feathers, Robin Money, U. O. Money
Robin D.Craydle (Robbing the Cradle)
Robin Droppings
Robin Meeblind (Robbing Me Blind)
Robin Plunder
Robyn Banks
Rock (Rocco) Bottoms, Rock Pounder, Rock Stone
Rocky Beach, Sandy Beach
Rocky Mountain, Cliff Mountain
Rocky Rhoades
Rocky Rhoades
Rod N. Reel
Rod N. Tootheecore
Roger Overandout
Roman Holiday
Roman Holiday
Ron A. Muck (Run Amuck)
Rosa Shore (rows ashore)
Rose Bush
Rose Bush
Rose Bush, Rose Gardner
Rose Gardner
Rosemary Border
Rosie Peach
Rowan Boatman
Royal Payne
Ruben Mycock (Rubbing My Cock)
Rufus Leaking (!!)
Russell Ingleaves (Rustling Leaves)
Russell Leeves
Russell Sprout
Rusty Blades, Rusty Bridges, Rusty Carr, Rusty Dorr, Rusty Fossat, Rusty Fender
Rusty Carr
Rusty Irons, Rusty Keyes, Rusty Nail, Rusty Pipes, Rusty Steele
Rusty Nails
Ryan Carnation
Ryan Coke (Rye whiskey with Coca Cola)
Sadie Word (Say the Word)
Sal A. Mander
Sal Ami
Sal Ami (Salami)
Sal Minella, Sam Manilla, Sam & Ella's restaurant
Sal Sage (Sausage)
Sal T. Penuz (Salty Penis or Peanuts)
Sally Forth
Sally Forth
Sally Mander
Sam Dayoulpay (Some day you'll pay)
Sam Manilla (Salmonella)
Sam Pull (Sample)
Sam Urai (Samurai)
Samson Night (Samsonite)
Sandy Banks
Sandy Banks, Sandy Beech, Sandy Brown, Sandy Spring
Sandy Shaw
Sarah Bellum
Sarah Doctorinthehouse (Is There a Doctor in the House)
Sawyer B. Hind, Sawyer Dickey (even better, I. Sawyer Dickey)
Scott Shawn DeRocks (Scotch on the Rocks)
Seaman Sample (Semen Sample)
Sean Head
Seth Poole (poor guy has a lisp)
Seymour Bush (gynecologist), Seymour Butz (proctologist), Seymour Wiener (urologist)
Seymour Butts (See more butts)
Seymour Legg
Seymour Legg - see more leg...................
Shada Lear*
Shanda Lear (daughter of Bill Lear, inventor of the Lear jet)
Shandy Lear
Sharon Fillerup
Sharon Needles, Sharon Weed, Sharon A. Burger
Sharon Sharalike
Sheeza Freak (She's a Freak)
Sheila Blige
Sheri Cola (Cherry Cola)
Sherman Wadd Evver (Sure Man, Whatever)
Shirley Knot (Surely not?)
Shirley U. Jest
Shirley U. Jest (Surely You Jest)
Sid Down (Sit Down)
Simon Swindells
Sir Fin Waves (Surfin' Waves)
Skip Roper, Skip Stone
Sno White (real person)
Sonny Day
Sonny Day (sunny day)
Stacey Rhect (Stays Erect)
Stan Dup (Stand up)
Stan Still - should own a 'stationery' store :->)
Stan Still - stand still as in an Army Sergeant-Major: 'Stand still you 'orrible little man.'
Stanley Cupp
Stella Constellation
Stu Padasso (Stupid Asshole)
Stu Pit
Stu Pitt (Stupid)
Sue Case (Suitcase)
Sue E. Side (Suicide)
Sue Flay
Sue Permann (Superman)
Sue Render (surrender, a real person)
Sue Ridge (Sewage)
Sue Ridge (sewerage)
Sue Shi (Sushi)
Sue Yourazzof (Sue Your Ass Off)
Sue Yu, Sue Jeu
Summer Camp (allegedly a real person), Summer Day, Summer Greene, Summer Holiday
Sy Burnette
Tad Moore
Tad Pohl
Tamara Knight
Tanya Hyde
Tanya Hyde
Tanya Hyde (Tan Your Hide)
Tanya Hyde (tan your hide)
Tara Cherry, real gynecologist
Tara Newhall (Tear a New Hole)
Tate Urchips (Tater Chips)
Taylor Maid
Ted E. Baer
Ted E. Baer
Ted E. Baer (Teddy Bear)
Teddy Bear
Telly Vision (Television)
Teresa Green
Teresa Green (Trees are Green)
Terri Bull
Terry Achey (real name)
Terry Bill - Will's friend from Portchester, England
Terry Bull (allegedly real name, and his brother Eddie Bull)
Terry Bull (terrible)
Tess Steckle
Tess Tickle (Testicle)
The Ng family--Bob, Buck, Bill, Frank, Stew, Fuk 
Theresa Green or Brown
Therese R. Green, Teresa Green
Thomas Richard Harry
Thor Luther
Tiffany Box (a real person, see THIS)
Tim Burr
Tim Burr
Tim Burr (Timber)
Tim Burr (timber)
Tina See (Tennessee)
Tish Hughes
Tittsworth & Grabbe, real law firm
Titus Balsac (Tightest Ball Sack)
Tom A. Toe
Tom Katt
Tom Katz (tom cats)
Tom Morrow
Tom Morrow (tomorrow)
Tommy Gunn
Tommy Hawk
Torah Hyman (Tore a Hymen)
Trina Forest (tree in a forest)
Trina Woods, Trina Forest (tree in the woods, tree in a forest)
Ty Coon 
Ty Coon, Ty Knotts
Ty Knotts (tie knots)
Ty Malone (time alone)
Ty Tannick (Titanic)
Ty Tass (Tight Ass)
Tyrone Shoes (Tie Your Own Shoes)
U.P. Freehly (You Pee Freely)
Ulee Daway (You Lead the Way)
Urich Hunt
Val Crow (Velcro)
Val Lay (Valet)
Val Veeta (Velveeta)
Viola Solo
Virginia Beach
Vlad Tire (Flat Tire)
Walt Smedley (waltz medley)
Walter Melon
Walter Melon (Watermelon)
Wanda Rinn
Wanna Hickey
Warren Peace
Warren Peace (war and peace)
Warren Piece (War and Peace)
Warren T.
Wayne Deer (Reindeer)
Wayne Kerr (Wanker)
Will Power
Will Power
Will Race (real person who told me he races cars and on foot)
Will U. Shuddup
Will Wynn (Mayor of Austin, Texas)
Willie B. Hardigan
Willie Leak (or won't he)
Willie Maykit (Will He Make It?)
Willie Stroker
Willie Stroker
Willie Waite
Wilma Leggrowbach (Will My Leg Grow Back?)
Winnie Bago (Winnebago)
Winnie Dipoo (Winnie the Pooh)
Winsom Cash, Owen Cash
Woody Bush
Woody Forrest
Woody Forrest
Woody U. No (What Do You Know?)
X. Benedict
Xavier Breath (Save Your Breath)
Xavier Money (Save Your Money)
Yerma Wildo (Your Mom Will Do)
Yousuckmynuts N. Scratchm (You Suck My Nuts and Scratch Them)
Yule B. Sari (You'll Be Sorry)
Zeke N. Yeshallfind (Seek and You Shall Find)
Zelda Kowz (Sell the Cows)
Zoe Mudgett Hertz (so much it hurts).
Zoltan Pepper (Salt and Pepper)
